Repository aws-controllers-k8s/runtime, pull requests merged in 2021-05, with the labels that each got.

#16 Add OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file

#12 Namespace scope service controllers
  pkg/config/config.go
  pkg/runtime/adoption_reconciler.go
  pkg/runtime/cache/cache.go
  pkg/runtime/cache/namespace.go
  pkg/runtime/cache/namespace_test.go
  pkg/runtime/reconciler.go
Labels: approved

#18 Add `pkg/compare/Path.MarshalJSON` function to implement `json.Marshaler` interface
  pkg/compare/path.go
Labels: approved, lgtm

#19 export IsNil and IsNotNil
  pkg/compare/nil.go
Labels: approved, lgtm

#17 Add new condition ACK.Advisory
  apis/core/v1alpha1/conditions.go
Labels: approved, lgtm
