Repository aws-controllers-k8s/runtime, pull requests merged in 2021-07, with the labels that each got.

#21 Returning the latest resource from the Delete() call
  mocks/pkg/types/aws_resource_manager.go
  pkg/runtime/reconciler.go
  pkg/types/aws_resource_manager.go
Labels: approved, lgtm

#30 fix for #866 - nil Interface check during delete
  pkg/runtime/reconciler.go
Labels: approved, lgtm

#31 Refactor reconciler.patchResource() to handle both Spec and Status patching
  Makefile
  mocks/controller-runtime/pkg/client/client.go
  mocks/controller-runtime/pkg/client/status_client.go
  mocks/controller-runtime/pkg/client/status_writer.go
  pkg/compare/map.go
  pkg/compare/map_test.go
  pkg/compare/meta.go
  pkg/compare/meta_test.go
  pkg/compare/slice.go
  pkg/compare/slice_test.go
  pkg/runtime/reconciler.go
  pkg/runtime/reconciler_test.go
Labels: approved, lgtm

#32 Reduce the number of instantiated/used `ackrtcache.Caches` objects.
  pkg/runtime/adoption_reconciler.go
  pkg/runtime/cache/cache.go
  pkg/runtime/reconciler.go
  pkg/runtime/reconciler_test.go
  pkg/runtime/service_controller.go
Labels: approved, lgtm

#33 New error code for Secret not found
  pkg/errors/error.go
  pkg/runtime/reconciler.go
Labels: approved, lgtm, needs-ok-to-test

#34 Fix reusing merge objects for patch without copying
  pkg/runtime/reconciler.go
  pkg/runtime/reconciler_test.go
Labels: approved, lgtm

#35 Add inline comments for deep copy patching
  pkg/runtime/reconciler.go
Labels: approved, lgtm

#36 Allow endpointURL to be specified in namespace annotations
  apis/core/v1alpha1/annotations.go
  pkg/runtime/adoption_reconciler.go
  pkg/runtime/cache/namespace.go
  pkg/runtime/cache/namespace_test.go
  pkg/runtime/reconciler.go
Labels: approved, lgtm, ok-to-test

#38 cleanups and DRYing up the reconciler unit tests
  mocks/pkg/types/aws_resource_descriptor.go
  pkg/runtime/reconciler.go
  pkg/runtime/reconciler_test.go
  pkg/types/aws_resource_descriptor.go
Labels: approved, lgtm

#39 simplify patching spec and status in reconciler
  mocks/pkg/types/aws_resource_reconciler.go
  pkg/runtime/reconciler.go
  pkg/runtime/reconciler_test.go
  pkg/types/aws_resource_reconciler.go
Labels: approved, lgtm
