Repository aws-controllers-k8s/runtime, pull requests merged in 2021-06, with the labels that each got.

#20 fix Delta.DifferentAt behavior via changes to Path.Contains
  pkg/compare/delta_test.go
  pkg/compare/path.go
Labels: approved, lgtm, ok-to-test

#22 additional logging in core reconciler
  mocks/pkg/types/logger.go
  mocks/pkg/types/trace_exiter.go
  mocks/pkg/types/tracer.go
  pkg/runtime/log/context.go
  pkg/runtime/log/noop.go
  pkg/runtime/log/resource.go
  pkg/runtime/reconciler.go
  pkg/types/logger.go
  pkg/types/tracer.go
Labels: approved

#24 add common ACK pkg/condition
  mocks/pkg/types/aws_resource.go
  mocks/pkg/types/condition_manager.go
  pkg/condition/condition.go
  pkg/condition/condition_test.go
  pkg/types/aws_resource.go
  pkg/types/condition_manager.go
Labels: approved, lgtm

#23 Adds logic to the reconcile function to handle the optional infinite requeue (Issue #826)
  pkg/runtime/reconciler.go
  pkg/types/aws_resource_manager.go
Labels: approved, lgtm, needs-ok-to-test

#25 Add two controller flags to enable and configure the webhook server
  pkg/config/config.go
Labels: approved, lgtm

#26 Add a `pkg/webhook` package to standardize the way controllers create and register new webhooks
  pkg/webhook/registry.go
  pkg/webhook/webhook.go
Labels: approved, lgtm

#27 Regenerate mocks package
  mocks/pkg/types/aws_resource_manager_factory.go
Labels: approved, lgtm

#29 Add `GetHostPort` function to extract the host and port from network addresses
  pkg/util/address.go
  pkg/util/address_test.go
Labels: approved, lgtm

#28 Delete `--bind-port` flag
  pkg/config/config.go
Labels: approved, lgtm

#13 Add additional keys to adopted resource spec
  apis/core/v1alpha1/identifiers.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/services.k8s.aws_adoptedresources.yaml
  pkg/runtime/adoption_reconciler.go
Labels: approved, lgtm
